services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: examplepass  
      MYSQL_DATABASE: example_db
      MYSQL_USER: example
      MYSQL_PASSWORD: examplepass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf:ro
volumes:
  mysql_data: 